### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [IOINITID/quick-links#1]
Hi,<br><br>url : https://github.com/IOINITID/quick-links/blob/6469ded735646e996f030fe540512270110f797f/config/default.json <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by IOINITID** [comment]
Hi, thanks, i know that, but this is just an open source project)
